---
- name: OpenVPN Install
  hosts: localhost

  vars:
    IP: "{{ IP }}"
    EMAIL: "{{ EMAIL }}"

  tasks:

  - name: Install EPEL
    yum:
      name: epel-release
      state: present

  - name: Install NGINX
    yum:
      name: nginx
      state: present

  - name: Start NGINX
    service:
      name: nginx
      state: started

  - name: Install Sendmail if EMAIL Provided
    yum:
      name: sendmail
      state: present
    when: EMAIL != "None"

  - name: Start Sendmail
    service:
      name: sendmail
      state: started
    when: EMAIL != "None"
  
  - name: Add Email Content
    shell: IP=$(hostname -I | cut -d' ' -f1); echo -e 'Subject:'' VPN Client Download'"\n"'Download Link:'" http://$IP/client.ovpn" >> email.txt
    when: EMAIL != "None"

# iptables -A INPUT -p tcp --dport 8000 -s 1.2.3.4 -j ACCEPT
  - iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 80
      source: "{{ IP }}"
      jump: ACCEPT
    become: yes

# iptables -A INPUT -p tcp --dport 80 -j DROP
  - iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 80
      jump: DROP
    become: yes

  - name: Check if OpenVPN Exists
    stat: 
      path: /usr/sbin/openvpn
    register: openvpn_status

  - name: Download OpenVPN Installer
    get_url:
      url: https://raw.githubusercontent.com/LopezNathan/vpn-deployer/master/openvpn-install.sh
      dest: /root/openvpn-install.sh
      mode: 0755
    when: openvpn_status.stat.exists == False

  - name: Run OpenVPN Installer
    environment:
      AUTO_INSTALL: y
    script: /root/openvpn-install.sh
    when: openvpn_status.stat.exists == False

  - name: Copy OpenVPN Config to NGINX Path
    copy:
      src: /root/client.ovpn
      dest: /usr/share/nginx/html/client.ovpn
    
  - name: Send Email About File Download
    shell: sendmail "{{ EMAIL }}" < /root/email.txt
    when: EMAIL != "None"